Add readme/gitattributes
happtiq/happtiq-oss-python-libs pull request #9
Opened 2024-08-22 14:53 UTC by kaanHapptiq

2024-08-22 15:01 UTC, dkleuser commented on .gitattributes
> +
Let's add some more Python specifics:
```suggestion
*.pxd    text diff=python eol=lf
*.py     text diff=python eol=lf
*.py3    text diff=python eol=lf
*.pyw    text diff=python eol=lf
*.pyx    text diff=python eol=lf
*.pyz    text diff=python eol=lf
*.pyi    text diff=python eol=lf

*.db     binary
*.p      binary
*.pkl    binary
*.pickle binary
*.pyc    binary export-ignore
*.pyo    binary export-ignore
*.pyd    binary
```

2024-08-22 15:02 UTC, dkleuser commented on .gitattributes
> +*.py text eol=lf
Either remove it in favour of the suggestion I posted below or add the `diff=python` here and remove the line for .py from my suggestions.

2024-08-23 06:51 UTC, mab-happtiq requested changes

2024-08-23 06:51 UTC, mab-happtiq commented on README.md
> +## Sub-Packages
```suggestion
## Packages
```

2024-08-23 06:51 UTC, mab-happtiq commented on README.md
> +[Read the README.md](https://github.com/happtiq/happtiq-oss-python-libs/blob/main/packages/happtiq_commons_gen_ai/README.md)
delete

2024-08-23 06:51 UTC, mab-happtiq commented on README.md
> +[Read the README.md](https://github.com/happtiq/happtiq-oss-python-libs/blob/main/packages/happtiq_commons_google_cloud/README.md)
delete

2024-08-23 06:51 UTC, mab-happtiq commented on README.md
> +`happtiq_commons_gen_ai` provides an interface to interact with different AI models like ChatGPT and Gemini. It includes methods to send prompts and manage responses.
delete

2024-08-23 06:51 UTC, mab-happtiq commented on README.md
> +`happtiq_commons_google_cloud` provides utilities and services to interact with various Google Cloud Platform services, including OAuth2 authentication, Google Cloud Storage (GCS) operations, Pub/Sub
delete

2024-08-23 06:51 UTC, mab-happtiq commented on README.md
> +This project is composed of two sub-packages, each providing specific functionalities to enhance your applications. Below are links to the respective sub-packages:
```suggestion
Below are links to the different packages:
```

2024-08-23 08:14 UTC, kaanHapptiq commented on README.md
> +## Sub-Packages
done in the branch

2024-08-23 11:21 UTC, mab-happtiq commented on .github/workflows/publish_pypi.yml
> +      with:
revert

2024-08-23 11:37 UTC, mab-happtiq requested changes

2024-08-23 11:37 UTC, mab-happtiq commented on README.md
> +[Learn more about happtiq_commons_gen_ai](https://github.com/happtiq/happtiq-oss-python-libs/tree/main/packages/happtiq_commons_gen_ai) (Link to documentation or GitHub repository).
```suggestion
[happtiq_commons_gen_ai](https://github.com/happtiq/happtiq-oss-python-libs/tree/main/packages/happtiq_commons_gen_ai)
```

2024-08-23 11:37 UTC, mab-happtiq commented on README.md
> +[Learn more about happtiq_commons_google_cloud](https://github.com/happtiq/happtiq-oss-python-libs/tree/main/packages/happtiq_commons_google_cloud) (Link to documentation or GitHub repository).
```suggestion
[happtiq_commons_google_cloud](https://github.com/happtiq/happtiq-oss-python-libs/tree/main/packages/happtiq_commons_google_cloud)
```

2024-08-26 11:31 UTC, dkleuser approved these changes

2024-08-26 11:41 UTC, mab-happtiq approved these changes

2024-08-27 07:46 UTC, merged